---
title: "Teaching Resources"
---


On this page I've compiled all the course materials for two workshops I have taught for graduate students at FSU, as well as other resources I've made for teaching.

## [Basic Computing with R](https://austin-cutler.quarto.pub/summer-ri-workshop/)

This workshop is for incoming first year PhD students to FSU. This workshop assumes no prior R experience and is designed to give incoming first year students a head start on learning to us R and Rstudio. The workshop covers installing R, basic functions in R, reading data into R, types of data, data cleaning, generating summary statistics, boolen logic, data visualization, for loops, and (briefly), writing functions in R. We also briefly cover expectations for graduate student life in general, and some aspects of using R that are tangentially related, such as computer file structures. The workshop is taught primarily using `tidyverse`, however for most applications the BaseR equivalent is also covered. The workshop is taught over four sessions, and the goal is for students to have a solid foundation for how R works before moving on to their first semester where they will solidify the skills taught in the class. I taught this workshop in the summer of 2023 and 2024, and helped develop the materials for the workshop for summer 2025.

## [Advanced Computing with R](https://austin-cutler.quarto.pub/summer-rii-workshop/)

This workshop is for rising second year PhD students, and builds off of the material covered in the RI workshop, as well as their classes throughout their first year. The goal of this workshop is to be a refresher on R for grad students after taking some time off, and to prepare them for taking MLE. Grad students who are not starting their second year have also taken it in the past. The workshop covers different data structures, for loops, data simulations, creating functions, and optimization.

## [Multivariate Regression Visualization](https://austin-cutler.shinyapps.io/Multiple_Regression_Visualization/)

I made a shinyapp that allows you to visualize multivariate regression with 2 independent variables. You can vary the slope for each variable, the sample size, and the y-intercept. I've used this to teach multivariate regression and feel that it helps students better understand what it means to "control for" additional variables. I plan to update it eventually to show some diagnostics of the model or to demonstrate the problems with omitted variable bias. The default regression that it estimates is: $Y\sim1+2X-5Z$.

## [Dice Rolling Statistics](https://austin-cutler.shinyapps.io/die_roll_check_sim/)

I threw together a shinyapp that serves two functions. First, you can manually enter in the frequency of dice rolls to get summary statistics from them. I did this to make grading one of the problem sets for my research methods class a little easier, making it so I just need to enter their data in and check their results rather than getting the values by hand. The second use of this app is you can simulate dice rolls for a large number of samples, setting the size of each sample. This allows you to show in real time how the central limit theorem and law of large numbers works. I'm confident similar tools exist, but thought this was neat.