---
title: "Research"
---
```{=html}
<style>
  /* Hide the title element on the page */
  .title {
    display: none;
  }
</style>
```

## Working Papers

- The Effect of Candidate Ideological Extremism on Vote Choice and Turnout (with Hans J.G. Hassell and Kevin Reuning)

    [This paper uses CES data from 2010 to 2022 to examine how voters' perception of candidates' ideological extremity influences their turnout and vote choice.]{style='color:gray'} [Link to paper.](https://www.dropbox.com/scl/fi/4vlq73wrfprx04hboxlan/CHR__Political_Extremism_Penalty_.pdf?rlkey=gqp8x5i6wd8anktrkjn0m71dk&e=2&dl=0)

---

- Who’s in Office Anyways? Estimating the Race of Elected Officials from Names with Neural Networks

    [In this paper, I use data from the Florida voter file and the Candidates Characteristics Cooperative (C3) to estimate the race of state legislative officials using their names by training a BiLSTM model on both the voter file and the C3 data. I compare this approach to other approaches of race estimation using names, and find that in most cases, race predictions improve when using state legislator data. I then analyze how these different strategies for estimating race may impact findings, namely electoral outcomes.]{style='color:gray'} [Link to Polmeth 41 Poster](https://www.dropbox.com/scl/fi/sx7si7lnoqmdv1e1r2r7z/cutler_polmeth_poster_24.pdf?rlkey=bwjafw8rsuc4w98bmix74nn9e&dl=0)

---

- Creating Interactive Data Dashboards with Ballot Images (with Lonna Atkeson, Yimeng Li, Wendy Hansen, Lisa Bryant, and Carson Cary)

    [In this project, we develop best practices for displaying ballot images online to improve transparency in elections. To do this, we develop interactive dashboards to display ballot images online, along with audit data and the cast vote record. The two primary hurdles we address are the protection of voters privacy, and preparing the data for presentation. When showing ballot images, people may sign their names when they should not, which results in a violation of their privacy. The data is also very large, making it a challenge to prepare it in such a way that it can be easily presented. This project is currently under contract as a cambridge elements piece. The link to our website where the dashboards are currently hosted is [here](https://www.voterdata.lci.fsu.edu/), and our technical report about the pilot project for the dashboard can be found [here](https://lrci-main-web-app.s3.us-east-1.amazonaws.com/23-LCI-002-Audit-Technical-Report-V1_4_LA2.pdf).]{style='color:gray'}

---

- Affective Policy Preferences: How Group Affect Can Shape Policy Positions

    [Using ANES panel data, and an original survey experiment, I try to improve our understanding of the relationship between affective polarization and public opinion. Using cross lagged panel models, I find that affective polarization consistently predicts people's policy positions. Furthermore, I when separately analyzing the effect of in-party and out-party affect, I find that in-party affect is a stronger predictor of people's policy positions. These findings from observational analysis are cooberated by a survey experiment.]{style='color:gray'}
---

## Conference Posters/Slides

[Below are some papers that I have conferenced recently, with a brief description with the slides, poster, or both attached, when possible. Only papers that have not made it past the conference paper stage are included below.]{style='color:gray'}

- Party Cues or Group Sympathy? How Perceived Group Support Shapes Policy Beliefs

    [This paper is a chapter of my dissertation where I explore the mechanism through which perceptions of social group support for a policy influence people's own policy positions. More specifically, I explore if racial group support for a policy influences people's own support for that policy due to people's attitudes towards that group, or if race is being used as a cue for party support. Using a vignette experiment, I find mixed evidence suggesting that race serves more as a party cue than directly influencing people's opinions.]{style='color:gray'} [Link to Polmeth 42 Poster](https://www.dropbox.com/scl/fi/ljly4gcd0xuacdsyggd75/cutler_polmeth_poster_25.pdf?rlkey=44uz4cb49a4qkqs5vhm1n9ejo&st=dhcnkyz9&dl=0)
    
- Seeing is Believing: Estimating the Effect of Misperceptions on Affective Poalrization Using Topic Sampling

    [Ahler and Sood (2018) is one of the most well cited papers in the affective polarization literature. The authors argue that correcting misperceptions about the out-party can reduce partisan animosity. However, it is unclear whether the observed effects are from the collection of demographic characteristics being correct, a single trait being corrected, or somewhere inbetween. Furthermore, as the authors note, the effect of correcting misperceptions is not statistically distinguishable from the effect of merely asking respondents their perceptions of the other parties. Both of these aspects of the original work need to be addressed, as they are crucial for understanding their results. In this paper, we propose a replication and extension of Ahler and Sood to a) improve power by increasing the sample size, which will make feasible to distinguish between the effect of asking about perceptions and correcting any misperceptions (if there is a difference) and b) using topic sampling to differentiate between the effect of different demographic groups to determine if any single group has a stronger effect on partisan affect. Presented at the annual meeting of the Southern Political Science Association, 2024.]{style='color:gray'}